### ISSUE TITLE
Unable to download from git.holy.how

### ISSUE THREAD

**Issue by SteadyStatus21** [holy-unblocker/website-aio#10]
```
npm ERR! code EHOSTUNREACH
npm ERR! syscall connect
npm ERR! errno EHOSTUNREACH
npm ERR! request to https://git.holy.how/attachments/npm_*** failed, reason: connect EHOSTUNREACH 5.161.79.176:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-09-28T13_26_25_946Z-debug-0.log
ubuntu@hub:~/website-aio$
```

Directly from terminal.

Maybe the host is down?

**Comment by HissingSoldier** [comment]
Yes, I believe that it is, I'm sure that everyone is unfortunately having this issue. Here is the link if you would like to check out what it is trying to download 

https://[git.holy.how](https://git.holy.how/attachments/7017bba8-f92a-4849-9d37-24bf47e437cb)/attachments/7017bba8-f92a-4849-9d37-24bf47e437cb

**Comment by SteadyStatus21** [comment]
> Yes, I believe that it is, I'm sure that everyone is unfortunately having this issue. Here is the link if you would like to check out what it is trying to download

https://[git.holy.how](https://git.holy.how/attachments/7017bba8-f92a-4849-9d37-24bf47e437cb)/attachments/7017bba8-f92a-4849-9d37-24bf47e437cb

Ah, completely understand. Thank you!

**Comment by e9x** [comment]
See #14.
