### ISSUE TITLE
Error: Unable to fetch the category data.

### ISSUE THREAD

**Issue by mydogisfast** [holy-unblocker/website-aio#11]
Thankfully, the proxy service works, but the apps and games sections load indefinitely, until the error "Unable to fetch the category data." appears. How might I fix this? I am hosting on heroku, and the games and apps sections worked previously. I do not know what changed, but something has. 
![image](https://user-images.githubusercontent.com/50509607/192829184-6ad54aea-1b48-42dd-8311-a6153dcd545d.png)
![image](https://user-images.githubusercontent.com/50509607/192829237-508fdfe9-5728-4586-a7ea-cf0c0e3e4d15.png)

**Comment by e9x** [comment]
See #14.
