### ISSUE TITLE
Server maintenance

### ISSUE THREAD

**Issue by e9x** [holy-unblocker/website-aio#14]
Our webserver is undergoing maintenance. This broke the Rammerhead and static frontend, which led to the temporary fix in 0ecb37ae691a16bffb12d349966ef39d5fb3ffae. Currently, the only feature that will not work is the game catalog. This will be fixed as soon as our webserver is online.

**Comment by NinjaDUDE97** [comment]
Okay, thx

**Comment by mydogisfast** [comment]
Thank you, my gratitude is inexpressible

**Comment by NinjaDUDE97** [comment]
^^same
the minute i read this i redeployed on Koyeb
I can't wait until koyeb releases the NYC region bc that is gonna make my app run much smoother

**Comment by e9x** [comment]
Our webserver is online. Website-aio is now fully operational.
