### ISSUE TITLE
Needs https to use?

### ISSUE THREAD

**Issue by popper69** [holy-unblocker/website-aio#15]
I'm running this proxy via my own network, it works flawlessly other than it needs https. How would I fix this?
(please dm me on Discord when you respond because I'm not active on github) My Discord is Skrill#0001
![image](https://user-images.githubusercontent.com/109952892/193940910-11bc8ac3-28c0-421c-8a46-2694a37bd513.png)

**Comment by HissingSoldier** [comment]
I’m not sure so don’t hold me to it, but I believe that it needs to be an actual link (https://www.yourdomain.com) instead of a ip (127.0.0.1). 

You could use a service that automatically gives you a **HTTPS** link not a **HTTP** link. I am sorry for not using the right terminology for some of these things but I believe that this will help you out.

**Comment by e9x** [comment]
> I'm running this proxy via my own network, it works flawlessly other than it needs https. How would I fix this? (please dm me on Discord when you respond because I'm not active on github) My Discord is Skrill#0001 ![image](https://user-images.githubusercontent.com/109952892/193940910-11bc8ac3-28c0-421c-8a46-2694a37bd513.png)

You can setup NGINX as a reverse proxy, however you will need a trusted certificate. I recommend certbot.

Alternatively, you can use Cloudflare to proxy your server and provide HTTPS.

**Comment by e9x** [comment]
> I’m not sure so don’t hold me to it, but I believe that it needs to be an actual link (https://www.yourdomain.com) instead of a ip (127.0.0.1).
> 
> You could use a service that automatically gives you a **HTTPS** link not a **HTTP** link. I am sorry for not using the right terminology for some of these things but I believe that this will help you out.

SSL certificates can be issued to IP addresses. I believe certbot covers this too.
