### ISSUE TITLE
this website sucks after change to koyeb

### ISSUE THREAD

**Issue by caden2010751** [holy-unblocker/website-aio#18]
nothing ever works fine now there is always a problem like it only runs in one language and if you try to change it it doesnt work and just stays the same that not even the only problem it decides to take 5 minitues to load one page or just doesnt load up at all and even it does there like a 30% chance it just wont work after (discord for a example) and a another problem it can barley run the simplest of apps like youtube or poki yeah it works but when you have wait what feels like an hour just for it to run at a shitty 480p and for poki lagging so hard its unimaginable idk why you switched to koyeb becuase it might not even be your fault it might be that koyeb is shit and also tab cloaks has like a 50/50 chance it wont work and dont even bother using anything other than ultraviolet becuase they dont even work

**Comment by e9x** [comment]
Deploy the website yourself! Our Koyeb instance is likely always being overloaded... You can join the TN Discord server and request an official HU link with dedicated resources.
