### ISSUE TITLE
Question: Will Stealth mode be added to AIO?

### ISSUE THREAD

**Issue by md4r2** [holy-unblocker/website-aio#19]
I noticed that there is no option for stealth mode and was wondering whether it would be added sometime in the future like the old HU. Is this going to be made available any time soon?

**Comment by e9x** [comment]
The new website builds off of the old website's stealth mode for proxying websites and launching apps. We can consider adding the other methods of loading the content such as "classic" and "about:blank".

**Comment by e9x** [comment]
I will leave this open to serve as a milestone for the above features.

**Comment by e9x** [comment]
Completed.

See 90a65d91a6738e0c3b5352fa48daaa0f6a9e8838
