### ISSUE TITLE
Error Loading Website

### ISSUE THREAD

**Issue by HissingSoldier** [holy-unblocker/website-aio#2]
Hello, I just installed this onto Replit and was very surprised at how well it functioned. I ended up running into an error trying to load a movie on SFlix, here is a screenshot. 

![image](https://user-images.githubusercontent.com/67211429/186563687-8b9577fb-bd0a-48c5-9d5b-054a82465d55.png)

I checked and videos are loading on YouTube worked so I'm not sure why this didn't work, I also checked on the site itself to make sure that it was working properly and it was. If anyone knows how to resolve this issue that would be amazing.

**Comment by e9x** [comment]
This is an issue with SFlix returning invalid HTML. This website may be removed from Holy Unblocker.

**Comment by HissingSoldier** [comment]
Okay, thanks!
