### ISSUE TITLE
How to get SSL Certificate for the host?

### ISSUE THREAD

**Issue by SteadyStatus21** [holy-unblocker/website-aio#21]
Hello!
I am trying to convert my domain from http:// into https://.
Is there a tool like certbot that can autorenew a ssl certificate and apply it for me?

Thanks,
SteadyStatus21

**Comment by SteadyStatus21** [comment]
What is your issue @crapmonster77?

**Comment by e9x** [comment]
> Hello! I am trying to convert my domain from http:// into https://. Is there a tool like certbot that can autorenew a ssl certificate and apply it for me?

Yes. Try [certbot](https://certbot.eff.org/). This script isn't configured to run under HTTPS, and really isn't intended to be exposed directly to the internet. Ideally you would use a reverse proxy like what the deployment services listed will do. I recommend you setup NGINX and configure it to proxy the website-aio script.

Here's an example config:
```nginx
# config w/letsencrypt
# HOSTNAME is a placeholder

server {
	listen 443 ssl http2;
	server_name HOSTNAME;

	location / {
		# Upgrade WebSockets
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'Upgrade';
		# Increase header buffer
		proxy_connect_timeout 10;
		proxy_send_timeout 90;
		proxy_read_timeout 90;
		proxy_buffer_size 128k;
		proxy_buffers 4 256k;
		proxy_busy_buffers_size 256k;
		proxy_temp_file_write_size 256k;
		# website script
		proxy_pass http://127.0.0.1:80;
	}
        
	ssl_certificate /etc/letsencrypt/live/HOSTNAME-0001/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/HOSTNAME-0001/privkey.pem;
	include /etc/letsencrypt/options-ssl-nginx.conf;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

**Comment by SteadyStatus21** [comment]
@e9x You are AMAZING!
Thank you so much!
-SteadyStatus21

**Comment by crapmonster77** [comment]
> What is your issue @crapmonster77?
@SteadyStatus21 
it just shows a gray screen

**Comment by e9x** [comment]
> > What is your issue @crapmonster77?
> > @SteadyStatus21
> > it just shows a gray screen

open a separate issue..
