### ISSUE TITLE
grey screen

### ISSUE THREAD

**Issue by crapmonster77** [holy-unblocker/website-aio#24]
when i go to the site it just shows a grey screen.

**Comment by e9x** [comment]
Are you deploying your own instance of website-aio or using the demo Koyeb instance?

**Comment by crapmonster77** [comment]
its https://website-aio.herokuapp.com/

**Comment by e9x** [comment]
> its https://website-aio.herokuapp.com/

That's one of our older instances, it seems to still be working on my end. What browser are you using? What version is your browser on?

**Comment by crapmonster77** [comment]
im using a chromebook so im using chrome browser

![Screenshot 2022-10-21 5 37 07 PM](https://user-images.githubusercontent.com/76125792/197292594-77ba0e2c-fcfc-4790-927c-edaa46edb330.png)

**Comment by e9x** [comment]
> im using a chromebook so im using chrome browser

What version of Chrome are you running?

**Comment by crapmonster77** [comment]
its the latest version i cant find the number tho

**Comment by crapmonster77** [comment]
also how do i use this site for me and my friends?

**Comment by MasterCubo** [comment]
Look in the docs for how to deploy on Replit or Heroku, those are the most new-user friendly imo. That heroku app link crashed and doesn't work anymore.

**Comment by e9x** [comment]
@crapmonster77 Like what @MasterCubo said, the official Heroku instance (the one you were attempting to use) is always being overloaded. Deploy your own instance.

**Comment by crapmonster77** [comment]
how do i deploy it from replit? (step by step?)

**Comment by e9x** [comment]
> how do i deploy it from replit? (step by step?)

Read the wiki. https://github.com/holy-unblocker/website-aio/wiki/Run-on-Replit
