### ISSUE TITLE
error.NotFoundError

### ISSUE THREAD

**Issue by Qdecillion** [holy-unblocker/website-aio#26]
![Screenshot 2022-10-24 4 16 30 PM](https://user-images.githubusercontent.com/116600004/197631232-c7f67eaa-77e1-44bc-be70-bd091cb5ef42.png)
This error message is shown when I try to run any website.

**Comment by e9x** [comment]
This must have been caused by an error when creating a Bare server.

**Comment by e9x** [comment]
This should be fixed with recent changes to how scripts are started.
