### ISSUE TITLE
the cloak dont work for me

### ISSUE THREAD

**Issue by pman5534** [holy-unblocker/website-aio#29]
it says (unable to cloak data) then some code

**Comment by e9x** [comment]
> it says (unable to cloak data) then some code

Can you provide us with the error code? Have you tried going to the URL that you entered for the cloak?

**Comment by pman5534** [comment]
it adds stuff and i dont know how to fix it

**Comment by pman5534** [comment]
![Screenshot 2022-11-15 8 34 48 AM](https://user-images.githubusercontent.com/117928600/201945873-d6957578-4d3b-4610-acb7-950aeb1efbf5.png)

**Comment by pman5534** [comment]
there we go. that is what it says.

**Comment by pman5534** [comment]
![Screenshot 2022-11-15 8 37 02 AM](https://user-images.githubusercontent.com/117928600/201946442-e2e8bc59-e569-4ffd-bfc6-eb3dd06840c8.png)

**Comment by pman5534** [comment]
that is what it says

**Comment by pman5534** [comment]
thats all i can find so far.

**Comment by e9x** [comment]
@pman5534 What URL are you entering for the cloak?
