### ISSUE TITLE
Failure registering the Ultraviolet Service Worker.

### ISSUE THREAD

**Issue by mydogisfast** [holy-unblocker/website-aio#3]
Error code in title. Comes up when attempting to open a blocked website.

**Comment by e9x** [comment]
How are you deploying website-aio?

**Comment by cjlop** [comment]
how am i supposed todeploy it just keep saying error

**Comment by mydogisfast** [comment]
I am deploying the fork I made from this repository through github pages.

> How are you deploying website-aio?

**Comment by e9x** [comment]
Although I am not sure how you are deploying this through GitHub pages, clearly you've gotten past the problem of starting the webserver on a static host. Fixed in #4
