### ISSUE TITLE
tab cloak

### ISSUE THREAD

**Issue by NinjaDUDE97** [holy-unblocker/website-aio#32]
would it be possible to make it so that we could insert the text for the tab cloak by ourselves?
like instead of giving a link and then the proxy finding the tab title on its own could it be made so that we could just insert "Math Homework" for the cloak instead?

**Comment by e9x** [comment]
This is possible, however the "enter a URL" design was chosen for simplicity. Perhaps this can be put on a TODO list.

**Comment by NinjaDUDE97** [comment]
Okay thx for letting me know
