### ISSUE TITLE
Replit Error

### ISSUE THREAD

**Issue by LmTechyTEMOG** [holy-unblocker/website-aio#33]
When I deploy this to replit in the terminal it says it cant find npm. When I do it manually when it boots using npm start it boots the website with a bunch of random text. I don't know what to do,

**Comment by ReysRamen** [comment]
My end is also doing the same, it says it encountered an error setting up the Nix environment and when it reads in start.js the import commands are undefined.

**Comment by logiadev** [comment]
try to update with npm update if that does not work then try npm audit fix

**Comment by e9x** [comment]
This should be fixed with recent changes to the .replit file.
