### ISSUE TITLE
repl.it: Blank white screen after about 30 seconds  Webpage: reloads the REPL

### ISSUE THREAD

**Issue by 24tiptlo** [holy-unblocker/website-aio#35]
My deployment is on replit.  For some reason, after clicking "Run", it would work completely fine for about 30 seconds where it would do two different things depending on what you were using:

On the Replit "Web View" window, it would display a blank white screen before showing the little replit robot and a loading bar.

On the actual webpage, it would stop loading certain things (like the twitter view, for example).  And when you tried to refresh, it would try to awake the REPL.

sometimes on both, it would load multiple robots.

![Screenshot 2022-12-07 4 48 15 PM](https://user-images.githubusercontent.com/102940069/206321762-3d208354-125d-462a-860f-24e701b5f739.png)
![Screenshot 2022-12-07 4 47 56 PM](https://user-images.githubusercontent.com/102940069/206321766-0ab11716-ed4a-4dee-862b-c9763aa9d5d8.png)
![Screenshot 2022-12-07 4 47 45 PM](https://user-images.githubusercontent.com/102940069/206321768-5a6847c1-b2ba-4f3d-9cc7-44df00154330.png)

It should be noted that this happened after I updated the fork.

I have tried updating the dependencies using `npm update` as well as `npm audit fix`.  I have also tried using one of my forks.

I am however **not** getting many errors.

I say many because once, I got an error saying it couldn't find a 404.html, and another time I got an error about the bare server node, however I haven't been able to recreate them.

**Comment by 24tiptlo** [comment]
I would also like to point out that [https://website-aio-e9x.koyeb.app/](https://website-aio-e9x.koyeb.app/) isn't working, as well as [https://website-aio.herokuapp.com/](https://website-aio.herokuapp.com/).  although, I can understand the herokuapp one is down because I heard they [removed free dynos](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq) in issue #34

**Comment by e9x** [comment]
This has something to do with how we start Rammerhead, exactly 30 seconds after the repl starts.

**Comment by e9x** [comment]
> I would also like to point out that https://website-aio-e9x.koyeb.app/ isn't working, as well as https://website-aio.herokuapp.com/.

The service isn't active due to the Railway account's inactivity. We will need to use a combination of CI and self-hosting to demo website-aio.
