### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by NinjaDUDE97** [holy-unblocker/website-aio#36]
Hello, I was just wondering why the proxy was not compatible with these two websites:
narrow.one
and
krunker.io
It used to work fine, now........not so much.

**Comment by NinjaDUDE97** [comment]
it still doesn't work with https://narrow.one

**Comment by e9x** [comment]
> it still doesn't work with https://narrow.one

Support for specific websites isn't guaranteed. Try switching the proxy engine by going to settings then selecting a different proxy.

**Comment by e9x** [comment]
If you still can't get the websites to work, this issue is beyond us and you should be making issues in the appropriate proxy repository.
