### ISSUE TITLE
Deploy to replit issue

### ISSUE THREAD

**Issue by Minemaster121** [holy-unblocker/website-aio#38]
The deploy to replut button works, but it is giving me the error "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'address' imported from /home/runner/website-aio-2/scripts/start.js". How to fix?

UPDATE: When I looked at the past issue about it, I used the tips given and it put the website into bare server mode. How to get out of bare server mode?

**Comment by 24tiptlo** [comment]
did you run "npm update" first?

**Comment by Minemaster121** [comment]
yes, and it put me into bare server mode, and I don't know how to get out of that mode.

**Comment by e9x** [comment]
@Minemaster121
You may need to pull the latest version of website-aio. Being put into "Bare server" mode was due to issues with ports.
Try the following:
```sh
$ git reset --HARD
$ git pull
```

```sh
$ npm install
# start the script with the start button or:
$ npm start
```

**Comment by blakeand32** [comment]
change the start.js to:
var urix = require("urix")

// On Windows:
urix("c:\\users\\you\\foo")
// /users/you/foo

// On unix-like systems:
urix("c:\\users\\you\\foo")
// c:\users\you\foo
