### ISSUE TITLE
SyntaxError : JSON.parse

### ISSUE THREAD

**Issue by CSystem77** [holy-unblocker/website-aio#39]
Hey,

I have error on proxy, you have idea ?

 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Site : https://celestedev.cf

Best regards,
CSystem.

**Comment by e9x** [comment]
> Hey,
> 
> I have error on proxy, you have idea ?
> 
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
> 
> Site : https://celestedev.cf
> 
> Best regards, CSystem.

Your Bare server (the script runs it on [/api/bare/](https://celestedev.cf/api/bare/) returns a 404. This is weird behavior and doesn't happen on a normal website-aio setup. I have tested it locally and I don't get an error on my instance.
