### ISSUE TITLE
Deploy to cyclic issue

### ISSUE THREAD

**Issue by pepe-the-saxophonist** [holy-unblocker/website-aio#41]
When I first deployed to cyclic it worked fine but the I redeployed and got an error saying "ERROR: Failed to run "npm run start". Start script defined in package.json:

            "scripts": {
                "start":  "node scripts/start.js"
                 ...
            
Exited with code: 7". Can anyone help?

**Comment by SteadyStatus21** [comment]
You are running a package manager (npm). You need to run `node scripts/start.js` for it to start, and if you want it to stay persistent after you close the terminal, install pm2 and run `pm2 start scripts/start.js`. 

-SteadyStatus21

**Comment by e9x** [comment]
They're doing this via cyclic. There isn't a repl-like interface. This is likely some Cyclic quirk due to how fast they're adding features.

**Comment by Sammuel-ay** [comment]
Ninjadude said ur a bozo e9x.
