### ISSUE TITLE
unable to open

### ISSUE THREAD

**Issue by BeanosTheGod** [holy-unblocker/website-aio#42]
Because of the title I can't deploy it using the main link and all other forms of code got blocked as well, is there a way an alternative link can be made that tricks the system, like changing the copying the code and making another site with another name like "Holy Site" or something like that.

**Comment by Jamels** [comment]
This is mentioned in the [docs](https://github.com/holy-unblocker/website-aio/wiki/Circumventing-deployment-restrictions).
Fork this repo and name it whatever.

**Comment by e9x** [comment]
This error is too broad and will not be fixed.
