### ISSUE TITLE
i am either dumb or idk how to code

### ISSUE THREAD

**Issue by LU5ive** [holy-unblocker/website-aio#47]
so i tried using the cmd "PORT=80 npm start" but it didnt work for some reason can someone help me and explain

![Select C__Windows_system32_cmd exe 18_02_2023 09_39_22](https://user-images.githubusercontent.com/65912764/219850793-c99b5ebd-6fb8-4a90-81ad-a2a160ae329c.png)

**Comment by e9x** [comment]
on windows with CMD, you need to specify the environment variable differently
try
```
setx PORT 8080
npm start
```
