### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by jcob1** [holy-unblocker/website-aio#48]
I host this on codesandbox.io, and whenever I try to use the Ultraviolet proxy it says 'SyntaxError: Unexpected token < in JSON at position 0,' the Rammerhead proxy says 'sessions must come from the same IP' and the Stomp proxy says the same thing as the Ultraviolet proxy but just a little more in detail.

Also could you please add the learn to fly games to the flash games collection

**Comment by e9x** [comment]
I suspect codesandbox.io is ratelimiting you and Rammerhead is having issues with how codesandbox is load balancing. I think codesandbox is too complicated of a host for this.
