### ISSUE TITLE
Error when attempting to use Ultraviolet 

### ISSUE THREAD

**Issue by Craftzman7** [holy-unblocker/website-aio#5]
I get the following error when attempting to use my own self-hosted instance when the proxy is set to Ultraviolet 
`RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].`

**Comment by e9x** [comment]
This error is very common with Ultraviolet and isn't specific to website-aio.
Check:
- Your browser (Bare protocol is problematic with Firefox)
- Your instance isn't being exhausted of its resources

**Comment by Craftzman7** [comment]
> This error is very common with Ultraviolet and isn't specific to website-aio.
> 
> Check:
> 
> - Your browser (Bare protocol is problematic with Firefox)
> 
> - Your instance isn't being exhausted of its resources 

It works fine on my PC running the latest version of Firefox. It breaks when I attempt to use the latest version of Chrome on ChromeOS. Are they any workarounds to fix this that aren't using Rammerhead?

**Comment by e9x** [comment]
> > This error is very common with Ultraviolet and isn't specific to website-aio.
> > Check:
> > 
> > * Your browser (Bare protocol is problematic with Firefox)
> > * Your instance isn't being exhausted of its resources
> 
> It works fine on my PC running the latest version of Firefox. It breaks when I attempt to use the latest version of Chrome on ChromeOS. Are there any workarounds to fix this that aren't using Rammerhead?

Using Rammerhead simply won't fix this issue. Does this happen on all websites or is there one in particular?

**Comment by Craftzman7** [comment]
> > > This error is very common with Ultraviolet and isn't specific to website-aio.
> > > Check:
> > > 
> > > * Your browser (Bare protocol is problematic with Firefox)
> > > * Your instance isn't being exhausted of its resources
> > 
> > 
> > It works fine on my PC running the latest version of Firefox. It breaks when I attempt to use the latest version of Chrome on ChromeOS. Are there any workarounds to fix this that aren't using Rammerhead?
> 
> Using Rammerhead simply won't fix this issue. Does this happen on all websites or is there one in particular?

This happens on all websites.

**Comment by e9x** [comment]
I think its specific to your user account on your chromebook. Try with Chrome on your desktop (on a non-managed account). If it works there, then the issue is definitely with your chromebook's configuration.
Check:
- Chrome version
- Unusual extensions

**Comment by Craftzman7** [comment]
> I think its specific to your user account on your chromebook. Try with Chrome on your desktop (on a non-managed account). If it works there, then the issue is definitely with your chromebook's configuration. Check:
> 
> * Chrome version
> * Unusual extensions

I'll test on my desktop as soon as I get the chance. I am running Chrome version 102.0.5005.177 on the Chromebook. The only likely extensions to be interfering would be Cisco Umbrella or Securly.
