### ISSUE TITLE
Make support for Vercel

### ISSUE THREAD

**Issue by TrollAndHack** [holy-unblocker/website-aio#59]
Hi, and i am trying to deploy this to vercel but there seems to be no option for it, i am requesting for the staff to add it in as it is the only one the school has not blocked yet.

Thank you.

Vercel: https://vercel.com/

**Comment by brlxkn** [comment]
You cannot deploy to Vercel as it is a static host. See https://github.com/holy-unblocker/website-aio/wiki/Known-incompatible-services#vercel

**Comment by e9x** [comment]
yup. vercel is strictly static and this hosts the bare server and rammerhead
you can host the website repository yourself, as that builds static
but not websuite-aio
