### ISSUE TITLE
Help required.

### ISSUE THREAD

**Issue by legendcuzican13** [holy-unblocker/website-aio#60]
This is ***not*** an issue report, I'm simply in need of some help.

I've got holy unblocked setup with ```npm install``` and ```npm start```, but whenever I try to use the proxy I get this error:

![Screenshot 2023-05-12 10 42 59 AM](https://github.com/holy-unblocker/website-aio/assets/108838775/3e823cd0-78d0-4db2-8ee4-10888a5f633a)

Does anyone know to fix this error?

**Comment by Jamels** [comment]
It"s because your connecting to your VPS using http Ultraviolet requires you to be connected by https.
I can try to help but I dont know lots about Caddy and its an unsupported method to add https.

**Comment by legendcuzican13** [comment]
Thanks for the quick reply! Do you know how I would be able to run the node app on the HTTPS port?

**Comment by towelcodes** [comment]
You need an SSL certificate. I don't have any experience with Caddy but the best way to configure a SSL certificate would likely be to use a reverse proxy. [It seems like you should be able to easily set this up on Caddy](https://caddyserver.com/docs/quick-starts/https#the-reverse-proxy-command).

**Comment by legendcuzican13** [comment]
Oh thanks. I'll try this.

**Comment by vivbyte** [comment]
I just use rammerhead instead of ultraviolet.
