### ISSUE TITLE
How can you deploy on other website other than the ones given?

### ISSUE THREAD

**Issue by PhDPigeon** [holy-unblocker/website-aio#7]
tell me

**Comment by e9x** [comment]
Use your intuition. If you get a terminal, follow the instructions for deploying via terminal.

If you want us to add support for another deployment service, make sure it isn't in the [known incompatible services](https://github.com/holy-unblocker/website-aio/wiki/Known-incompatible-services) then send it here.

**Comment by e9x** [comment]
Closing this. Open a PR if you are adding configs/buttons for deploying to a new service. If you have a service in particular, open an issue and we will work on it.
