### ISSUE TITLE
Error with official heroku instance

### ISSUE THREAD

**Issue by md4r2** [holy-unblocker/website-aio#8]
Opened [https://website-aio.herokuapp.com/](https://website-aio.herokuapp.com/) and came up with the error:

An error occurred in the application and your page could not be served.

**Comment by e9x** [comment]
We are out of Heroku dynos! Hosting an official website-aio instance on free services has been a challenge.

**Comment by e9x** [comment]
Try our Koyeb instance: https://website-aio-e9x.koyeb.app/
